name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install -y libsdl2-dev libglu1-mesa-dev lua5.3 liblua5.3-dev cmake

      - name: Build
        run: |
          cd build
          cmake ..
          make
